services:
  backend:
    build:
      context: ../zuriapp-backend
    container_name: zuri-backend-compose
    ports:
      - "5000:5000"
    environment:
      PORT: 5000

  frontend:
    build:
      context: ../zuriapp-frontend
      args:
        VITE_API_URL: http://localhost:5000
    container_name: zuri-frontend-compose
    ports:
      - "8080:80"
    depends_on:
      - backend