apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuri-frontend
spec:
  replicas: 2
  selector:
    matchlabels:
      app: zuri-frontend
  template:
    metadata:
      labels:
        app: zuri-frontend
    spec:
      containers:
        - name: zuri-frontend
          image: erobhose/zuriapp-frontend:latest
          ports:
            - containerPort: 80